### ISSUE TITLE
Creating site with global database fails

### ISSUE THREAD

**Issue by mbtamuli** [EasyEngine/site-command#135]
### Steps to Reproduce

1. Get latest `develop-v4` branch and install requirements
```
git clone https://github.com/EasyEngine/easyengine.git
cd easyengine
git checkout develop-v4
composer install
```
2. Create site using `./bin/ee site create example.com --ssl=le --wildcard`
3. Create second site using `./bin/ee site create one.example.com --type=wp`
4. Create third site using `./bin/ee site create two.example.com --type=wp`

#### Actual Results

```
curl -s -IL https://two.example.com/ | grep -Fi link
link: <https://two.example.com/index.php?rest_route=/>; rel="https://api.w.org/"
curl -s -IL https://two.example.com/ | grep -Fi link
link: <https://one.example.com/index.php?rest_route=/>; rel="https://api.w.org/"
curl -s -IL https://two.example.com/ | grep -Fi link
link: <https://two.example.com/index.php?rest_route=/>; rel="https://api.w.org/"
curl -s -IL https://two.example.com/ | grep -Fi link
link: <https://one.example.com/index.php?rest_route=/>; rel="https://api.w.org/"
```

#### Expected Results

```
curl -s -IL https://two.example.com/ | grep -Fi link
link: <https://two.example.com/index.php?rest_route=/>; rel="https://api.w.org/"
curl -s -IL https://two.example.com/ | grep -Fi link
link: <https://two.example.com/index.php?rest_route=/>; rel="https://api.w.org/"
curl -s -IL https://two.example.com/ | grep -Fi link
link: <https://two.example.com/index.php?rest_route=/>; rel="https://api.w.org/"
curl -s -IL https://two.example.com/ | grep -Fi link
link: <https://two.example.com/index.php?rest_route=/>; rel="https://api.w.org/"
```

**Comment by mbtamuli** [comment]
After exploring this problem, here is what I understand. This problem has risen because we connected the site's PHP containers to the `global-network`. 

As both site's Nginx containers are on the same network and try to send FastCGI requests to [php:9000](https://github.com/EasyEngine/site-type-wp/blob/develop/templates/config/nginx/main.conf.mustache#L69), the request gets sent once to the first site's PHP container and the subsequent request gets sent to the second site's PHP container.

**Comment by mbtamuli** [comment]
As a resolution for this, we need to define separate networks.
1. Public facing
2. Internal network for communicating between global containers and site specific containers.
2. Site network for communication among site specific containers.

So, we can have a situation like this
```
ee-global-nginx-proxy     -> global-public
ee-global-db              -> global-internal
ee-global-redis           -> global-internal

onedevrtdemoin_nginx_1    -> global-public, site-network
twodevrtdemoin_nginx_1    -> global-public, site-network
twodevrtdemoin_postfix_1  -> site-network
onedevrtdemoin_mailhog_1  -> global-public, site-network
onedevrtdemoin_postfix_1  -> site-network
twodevrtdemoin_php_1      -> global-internal, site-network
onedevrtdemoin_php_1      -> global-internal, site-network
twodevrtdemoin_mailhog_1  -> global-public, site-network
```

**Comment by mbtamuli** [comment]
`docker-compose.yml` for global services. 

```
version: '3.5'

services:
  nginx-proxy:
    ...
    networks:
      - global-public
  global-db:
    ...
    networks:
      - global-internal

networks:
global-public:
external:
  name: ee-global-public-network
global-internal:
  external:
    name: ee-global-internal-network
 ```
_Note: Truncated keeping only parts related to issue,_

**Comment by mbtamuli** [comment]
`docker-compose.yml` for site

```
version: '3.5'

services:

  php:
    networks:
      - site-network
      - global-internal

  nginx:
    networks:
      - site-network
      - global-public

  mailhog:
    networks:
      - site-network
      - global-public

  postfix:
    networks:
      - site-network

networks:
  site-network:
    name: ${VIRTUAL_HOST}
    labels:
     - "org.label-schema.vendor=EasyEngine"
     - "io.easyengine.site=${VIRTUAL_HOST}"
  global-public:
  external:
    name: ee-global-public-network
  global-internal:
    external:
      name: ee-global-internal-network
```

_Note: Truncated keeping only parts related to issue,_
